GET http://localhost:8080/car/15
apiKey: [B@4c1c0b3
Content-Type: application/json

{
  "userRole": "ADMIN"
}

###

POST http://localhost:8080/car
apiKey: [B@4c1c0b3
Content-Type: application/json

{
  "userRole": "ADMIN",
  "car": {
    "name": "Kia",
    "number": "1111 AP-7",
    "numberArea": 3,
    "status": false
  }
}

###

PUT http://localhost:8080/car/1
apiKey: [B@4c1c0b3
Content-Type: application/json

{
  "userRole": "ADMIN",
  "car": {
    "id": 20,
    "name": "Audi A8",
    "number": "9955 AP-7",
    "numberArea": 4,
    "status": false
  }
}

###

DELETE http://localhost:8080/car/1
apiKey: [B@4c1c0b3
Content-Type: application/json

{
  "userRole": "ADMIN"
}

###

POST http://localhost:8080/car/sortName
apiKey: [B@5bf442bb
Content-Type: application/json

{
  "userRole": "ADMIN"
}

###

POST http://localhost:8080/car/sortNumberArea
apiKey: [B@3dfdae7b
Content-Type: application/json

{
  "userRole": "ADMIN"
}

###

POST http://localhost:8080/car/callCar
apiKey: [B@325aba4e
Content-Type: application/json

{
  "car": {
    "numberArea": 1,
    "status": false
  },
  "user": {
    "latitude": 53.886346,
    "longitude":27.427766
  }
}

###