#You can test the following requests in this http file:
#- car output by id
#- creating a new car
#- change
#- removal
#- sorting by name
#- sorting by Area number

GET http://localhost:8080/car/15
apiKey: [B@6f88d878
Content-Type: application/json

{
  "userRole": "ADMIN"
}

###

POST http://localhost:8080/car
apiKey: [B@6f88d878
Content-Type: application/json

{
  "userRole": "ADMIN",
  "car": {
    "name": "Kia",
    "number": "1111 AP-7",
    "numberArea": 3,
    "status": false
  }
}

###

PUT http://localhost:8080/car/1
apiKey: [B@6f88d878
Content-Type: application/json

{
  "userRole": "ADMIN",
  "car": {
    "id": 1,
    "name": "Audi A8",
    "number": "9955 AP-7",
    "numberArea": 4,
    "status": false
  }
}

###

DELETE http://localhost:8080/car/1
apiKey: [B@6f88d878
Content-Type: application/json

{
  "userRole": "ADMIN"
}

###

POST http://localhost:8080/car/sortName
apiKey: [B@6f88d878
Content-Type: application/json

{
  "userRole": "ADMIN"
}

###

POST http://localhost:8080/car/sortNumberArea
apiKey: [B@6f88d878
Content-Type: application/json

{
  "userRole": "ADMIN"
}

###