#You can test the following requests in this http file:
#- output the user id
#- creating a new user
#- change
#- removal
#- entrance
#- exit
#- sort by last name
#- calling a car
#- arrival of the user

GET http://localhost:8080/user/1
apiKey: [B@6f88d878

###

POST http://localhost:8080/user
Content-Type: application/json

{
  "userRole": "ADMIN",
  "firstName": "string",
  "lastName": "string",
  "email": "test@gmail.com",
  "password": "string",
  "token": null,
  "geolocationUser": {
    "latitude": 0.0,
    "longitude":0.0
  },
  "numberCar": null
}

###

PUT http://localhost:8080/user/1
apiKey: [B@6f88d878
Content-Type: application/json

{
  "userRole": "ADMIN",
  "user": {
    "id": 1,
    "userRole": "ADMIN",
    "firstName": "test-string",
    "lastName": "test-string",
    "email": "test-string@gmail.com",
    "password": "string",
    "token": "[B@6f88d878",
    "geolocationUser": {
      "latitude": 0.0,
      "longitude":0.0
    },
    "numberCar": null
  }
}

###

DELETE http://localhost:8080/user/2
apiKey: [B@6f88d878
Content-Type: application/json

{
  "userRole": "USER"
  }

###

POST http://localhost:8080/user/login
Content-Type: application/json

{
  "user": {
    "email": "test@gmail.com",
    "password": "string"
  }
}

###

POST http://localhost:8080/user/logout
apiKey: [B@6f88d878

###

POST http://localhost:8080/user/sortLastName
apiKey: [B@6f88d878
Content-Type: application/json

{
  "userRole": "ADMIN"
}

###

POST http://localhost:8080/user/callCar
apiKey: [B@535a11ae
Content-Type: application/json

{
  "car": {
    "numberArea": 1,
    "status": false
  },
  "user": {
    "geolocationUser": {
      "latitude": 53.886346,
      "longitude": 27.427766
    }
  }
}

###

POST http://localhost:8080/user/userArrived
apiKey: [B@535a11ae

###