GET http://localhost:8080/user/1
apiKey: [B@78df5f89

###

POST http://localhost:8080/user
Content-Type: application/json

{
  "userRole": "ADMIN",
  "firstName": "string",
  "lastName": "string",
  "email": "string@gmail.com",
  "password": "string",
  "token": null
  }

###

PUT http://localhost:8080/user/1
apiKey: [B@4c1c0b3
Content-Type: application/json

{
  "userRole": "ADMIN",
  "user": {
    "id": 1,
    "userRole": "ADMIN",
    "firstName": "Test-string",
    "lastName": "Test-string",
    "email": "Test-string@gmail.com",
    "password": "string",
    "token": "[B@4c1c0b3"
   }
  }

###

DELETE http://localhost:8080/user/2
apiKey: [B@4c1c0b3
Content-Type: application/json

{
  "userRole": "USER"
  }

###

POST http://localhost:8080/user/login
Content-Type: application/json

{
  "user": {
    "email": "string@gmail.com",
    "password": "string"
  }
}

###

POST http://localhost:8080/user/logout
apiKey: [B@4c1c0b3

###

POST http://localhost:8080/user/sortLastName
apiKey: [B@15dee39d
Content-Type: application/json

{
  "userRole": "ADMIN"
}

###